# Generated by Django 3.2.12 on 2022-05-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='secret',
            field=models.BooleanField(default=False, verbose_name='投稿者にのみ表示させる'),
        ),
    ]
